{{ config(materialized='table') }}

WITH final AS (
    SELECT
        contact_id,
        salutation,
        first_name,
        last_name,
        contact_name,
        email,
        title,
        phone,
        fax,
        mobile_phone,
        department,
        lead_source,
        birthdate,
        mailing_street,
        mailing_city,
        mailing_state,
        mailing_postal_code,
        mailing_country,
        mailing_state_code,
        mailing_country_code,
        other_street,
        other_city,
        other_state,
        other_postal_code,
        other_country,
        other_country_code,
        assistant_phone,
        assistant_name,
        home_phone,
        description,
        account_id,
        owner_id,
        created_date,
        created_by_id,
        last_modified_date,
        last_modified_by_id,
        system_modstamp,
        is_email_bounced,
        photo_url,
        clean_status,
        is_priority_record,
        contact_level,
        languages,
        last_viewed_date,
        last_referenced_date,
        last_activity_date,
        CURRENT_TIMESTAMP AS _loaded_at,
        '{{ invocation_id }}' AS _dbt_invocation_id,
        '{{ project_git_sha() }}' AS _git_sha
    FROM {{ ref('silver_salesforce_contact') }}
)

SELECT * FROM final